#' Visualize LPA groups
#' 
#' Creates visNetwork visualization of clusters generated by the LPA. 
#' Function requires graph generated with the lpa() function.
#' 
#' @param G lpa() output - igraph object with "group" label assigned to each node
 
visualize_lpa <- function(G) {
  
  data <- toVisNetworkData(G_new)
  visNetwork(nodes = data$nodes, edges = data$edges, height = "3000px", width = "100%") |>
    visIgraphLayout(layout = "layout_with_fr") |>
    visNodes(size = 10) |>
    visOptions(highlightNearest = list(enabled = T, hover = T), 
               nodesIdSelection = T, selectedBy = "group") |>
    visSave(file = "./network_1.html")
}